### ISSUE TITLE
bouton ajouter et annuler

### ISSUE THREAD

**Issue by Myandes** [Reytian1977/S1-Intro-main#1]
**Description générale**
le format des boutons ajouter et annuler ne correspond pas aux boutons du fichier final 

**Étapes pour reproduire le bogue**
Étapes:

**Comportement attendu**
image de format grand boutons 

**Comportement observé**

**Notes supplémentaires (optionnel)**

**Suggestions et/ou pistes de correction (optionnel)**

**Comment by Reytian1977** [comment]
tienes rason pero nunca me mostraron como hacerlo, pero voy a seguir el consejo de Maryse: va chercher sur internet

**Comment by Myandes** [comment]
¡así que seamos pacientes para la solución! Gracias por regresar.

**Comment by Reytian1977** [comment]
Désole mais les formats qu'on a resu sur le master sont inconnu pour moi alors je ne peux pas les modifier
