### ISSUE TITLE
java script absent

### ISSUE THREAD

**Issue by Myandes** [Reytian1977/S1-Intro-main#2]
**Description générale**
Vous n'avez pas joint de fichier java script

**Étapes pour reproduire le bogue**
Étapes:

**Comportement attendu**
fichier Java Script

**Comportement observé**

**Notes supplémentaires (optionnel)**

**Suggestions et/ou pistes de correction (optionnel)**

**Comment by Reytian1977** [comment]
Desolé

**Comment by Reytian1977** [comment]
c'est fait
